tinymce.addI18n('ru', {
    "Undo": "Отменить",
    "Redo": "Повторить",
    "Bold": "Жирный",
    "Italic": "Курсив",
    "Underline": "Подчёркнутый",
    "Strikethrough": "Зачёркнутый",
    "Superscript": "Надстрочный",
    "Subscript": "Подстрочный",
    "Clear formatting": "Очистить форматирование",
    "Align left": "По левому краю",
    "Align center": "По центру",
    "Align right": "По правому краю",
    "Justify": "По ширине",
    "Bullet list": "Маркированный список",
    "Numbered list": "Нумерованный список",
    "Decrease indent": "Уменьшить отступ",
    "Increase indent": "Увеличить отступ",
    "Link": "Ссылка",
    "Open link": "Открыть ссылку",
    "Edit link": "Изменить ссылку",
    "Remove link": "Удалить ссылку",
    "Insert link": "Вставить ссылку",
    "Insert/edit link": "Вставить/изменить ссылку",
    "Insert/edit image": "Вставить/изменить изображение",
    "Insert image": "Вставить изображение",
    "Insert video": "Вставить видео",
    "Insert table": "Вставить таблицу",
    "Table": "Таблица",
    "Delete table": "Удалить таблицу",
    "Insert row before": "Вставить строку выше",
    "Insert row after": "Вставить строку ниже",
    "Delete row": "Удалить строку",
    "Insert column before": "Вставить столбец слева",
    "Insert column after": "Вставить столбец справа",
    "Delete column": "Удалить столбец",
    "Heading 1": "Заголовок 1",
    "Heading 2": "Заголовок 2",
    "Heading 3": "Заголовок 3",
    "Heading 4": "Заголовок 4",
    "Heading 5": "Заголовок 5",
    "Heading 6": "Заголовок 6",
    "Paragraph": "Параграф",
    "Blocks": "Блоки",
    "Font sizes": "Размеры шрифта",
    "Font family": "Шрифт",
    "Source code": "Исходный код",
    "Insert template": "Вставить шаблон",
    "Templates": "Шаблоны",
    "Paste": "Вставить",
    "Copy": "Копировать",
    "Cut": "Вырезать",
    "Select all": "Выделить всё",
    "Find and replace": "Найти и заменить",
    "Find": "Найти",
    "Replace": "Заменить",
    "Print": "Печать",
    "Fullscreen": "Полноэкранный режим",
    "Visual aids": "Визуальные подсказки",
    "Remove format": "Удалить форматирование",
    "New document": "Новый документ",
    "Document": "Документ",
    "Format": "Формат",
    "Edit": "Изменить",
    "File": "Файл",
    "View": "Вид",
    "Tools": "Инструменты",
    "Table properties": "Свойства таблицы",
    "Cell properties": "Свойства ячейки",
    "Merge cells": "Объединить ячейки",
    "Split cell": "Разделить ячейку",
    "Row properties": "Свойства строки",
    "Column properties": "Свойства столбца",
    "Image description": "Описание изображения",
    "Image title": "Заголовок изображения",
    "Dimensions": "Размеры",
    "Width": "Ширина",
    "Height": "Высота",
    "Border": "Граница",
    "Alternative source": "Альтернативный источник",
    "Style": "Стиль",
    "Class": "Класс",
    "Target": "Цель",
    "Rel": "Rel",
    "Text to display": "Текст для отображения",
    "Url": "URL",
    "Open in new window": "Открыть в новом окне",
    "Enable spellchecker": "Включить проверку орфографии",
    "Spellcheck": "Проверка орфографии"
});
