/** Compatibility layer: re-export Lucide icons for Remnawave parity.

All remnawave frontend pages import from @/components/brand/icons.
This file re-exports the same icon names from lucide-react so pages
copied from the reference work without import changes.
*/
export {
  // Layout / navigation
  LayoutDashboard,
  Server,
  Settings,
  Terminal,
  Users,
  UserCog,
  Bot,
  // Finance
  Wallet,
  CreditCard,
  TrendingUp,
  TrendingDown,
  // Communication
  MessageCircle,
  Mail,
  BellRing,
  Megaphone,
  MessageSquare,
  // Actions
  Plus,
  Pencil,
  Trash2,
  Copy,
  Check,
  X,
  RefreshCw,
  ArrowLeft,
  ArrowRight,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  ArrowUpDown,
  ArrowRightLeft,
  Search,
  Filter,
  MoreVertical,
  Eye,
  ExternalLink,
  // Status / data
  Activity,
  HeartPulse,
  AlertCircle,
  ShieldAlert,
  ShieldCheck,
  ShieldBan,
  BarChart3,
  // Users & people
  UserPlus,
  User,
  // Content
  FileText,
  Folder,
  File,
  Menu,
  Image,
  Puzzle,
  Palette,
  Monitor,
  Package,
  Boxes,
  Network,
  // Misc
  Ticket,
  Gift,
  Star,
  Hash,
  AtSign,
  List,
  Crown,
  Sparkles,
  History,
  Square,
  Calendar,
  Clock,
  HardDrive,
  Smartphone,
  Share2,
  Key,
  ClipboardList,
  Zap,
  Sparkles as Sparkle,
  type LucideIcon,
} from 'lucide-react'